### ISSUE TITLE
Guarda Shielded: Transacting z2z results in sending error

### ISSUE THREAD

**Issue by BostonZcash** [guardaco/guarda-android-wallets#15]
When sending Zcash from an internal shielded address to an external shielded address, I receive the following error:

```
Sending error: src.length=2 srcPos=0
dst.length=192 dstPos=0 length=192
```

### Environment

**Device:** OnePlus 5T
**OS:** LineageOS 15.1 (Android 8.1.0) + Google Play Services
**Version:** Guarda Shielded ver. 1.20

### Steps to replicate

1. Install a fresh instance of Guarda Shielded (GS) on the above platform.
2. Create new wallet.
3. Deposit ZEC from an external shielded address to the GS shielded address.
4. After the transaction is confirmed and funds are seen in GS, go to Send, choose 'Send from Zcash Address', and scan a QR code of an external shielded ZEC address.
5. Send an amount below the balance, accounting for fees.
6. Upon pressing 'Confirm', receive the aforementioned toast error message. 

### Notes

- All z2z transactions have been unsuccessful on this device (attempted as above), despite app reinstallations, updates, clearing app data / cache, and generating fresh wallets.
- On two other devices (running LineageOS 14.1 and 16.0), I've not been able to even detect incoming z2z deposits to their wallets. This device is the closest I've gotten to sending a z2z.
- Prior to the latest update, instead of the `src.length` error, I had been consistently receiving: `Sending error: Attempt to invoke virtual method 'java.lang.String com.guarda.zcash.sapling.db.model.TxOutRoom.a()' on a null object reference`.

Thanks in advance!

**Comment by nighthawk24** [comment]
When sending Zcash from an internal shielded address to an external shielded address, I receive the following error:

> Sending error: 18:
> bad-txns-joinsplit-requirements-not-met.
> Code:-26

Device: Pixel 3a
OS: Android 10 Official
Version: Guarda Shielded ver. 1.21

Steps to replicate
Install a fresh instance of Guarda Shielded (GS) on the above platform.
Create new wallet.
Deposit ZEC from an external shielded address to the GS shielded address.
After the transaction is confirmed and funds are seen in GS, go to Send, choose 'Send from Zcash Address', and scan a QR code of an external shielded ZEC address.
Send an amount below the balance, accounting for fees.
Upon pressing 'Confirm', receive the aforementioned toast error message.
Notes
All z2z transactions have been unsuccessful on this device (attempted as above), despite app reinstallations, updates, clearing app data / cache, and generating fresh wallets.

Prior to the latest update, instead of the src.length error, I had been consistently receiving: Sending error: Attempt to invoke virtual method 'java.lang.String com.guarda.zcash.sapling.db.model.TxOutRoom.a()' on a null object reference.
Thanks in advance!

**Comment by samosudov** [comment]
Hello!

Thank you for your feedback.

@BostonZcash Check please last version 1.21. There was an issue with sending to z address in 1.20.

@nighthawk24 We had an issue on the server side. It's synced now and works fine. Sync your wallet and check it out.

Thanks!

**Comment by guardawallet** [comment]
Hello!

Thank you for your feedback.

@BostonZcash Check please last version 1.21. There was an issue with sending to z address in 1.20.

@nighthawk24 We had an issue on the server side. It's synced now and works fine. Sync your wallet and check it out.

Thanks!
